Adneom.Adneotheque.Web/Controllers/BorrowController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Domain.Models.Item;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class BorrowController : Controller
    {
        [HttpGet]
        // GET: Borrow/SendNotification/1
        public ActionResult SendNotification(int id)
        {
            if (ModelState.Count < 1) return RedirectToAction("Search");

            ItemService itemService = new ItemService();
            if (itemService.SendNotification(id))
                return View("SendNotificationSuccessView");
            else
                return View("SendNotificationErrorView");
        }

        [HttpGet]
        public ActionResult Apply(int id)
        {
            if (ModelState.Count < 1) return RedirectToAction("BorrowErrorView");

            ItemService itemService = new ItemService();
            if (itemService.UpdateForBorrow(id))
                return View("BorrowSuccessView");
            else
                return View("BorrowErrorView");
        }
    }
}

Adneom.Adneotheque.Web/Controllers/ReturnController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Domain.Models.Item;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class ReturnController : Controller
    {
        // GET: Return
        public ActionResult Index()
        {
            IList<ItemResultModel> itemItemResultModelList = new List<ItemResultModel>();
            ItemService itemService = new ItemService();
            itemItemResultModelList = itemService.GetItemsToReturn();
            return View(itemItemResultModelList);
        }

        [HttpGet]
        // GET: Return/Apply/1
        public ActionResult Apply(int id)
        {
            if (id < 1) return RedirectToAction("Index");

            ItemService itemService = new ItemService();

            if (itemService.UpdateForReturn(id))
                return View("ReturnSuccessView");
            else
                return View("ReturnErrorView");
        }
    }
}

Adneom.Adneotheque.Web/Controllers/SearchController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Common.Helpers;
using Adneom.Adneotheque.Domain.Models.Item;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(ItemSearchModel itemSearchModel)
        {
            ItemService itemService = new ItemService();
            IList<ItemResultModel> itemResultList = new List<ItemResultModel>();

            if (!string.IsNullOrEmpty(itemSearchModel.SearchKey))
                itemResultList = itemService.GetItemToBorrow(itemSearchModel);
            else
                itemResultList = itemService.GetAll();

            itemResultList = itemService.GetUniqueResult(itemResultList);

            ViewBag.LanguageFilters = itemService.GetLanguageFilters(itemResultList);
            ViewBag.CategoryFilters = itemService.GetCategoryFilters(itemResultList);

            itemResultList = itemService.GetFilterResult(itemResultList);

            #region Pagination
            ViewBag.CurrentPage = 1;
            ViewBag.TotalPageCount = 1;
            ViewBag.ShowPagination = false;
            if (itemResultList != null && itemResultList.Count > ItemService.ItemCountForSearchResult)
                ViewBag.ShowPagination = true;

            if (itemResultList != null && itemResultList.Count > 0)
            {
                int i = itemResultList.Count / ItemService.ItemCountForSearchResult;
                decimal d = (decimal)itemResultList.Count / (decimal)ItemService.ItemCountForSearchResult;

                if (d > i)
                {
                    i = i + 1;
                }

                ViewBag.TotalPageCount = i;
            }

            string paginationQueryValue = CommonHelpers.GetCurrentQueryParameter(ItemService.PaginationQueryString);

            if (!string.IsNullOrEmpty(paginationQueryValue))
            {
                int pageValue = 0;
                int.TryParse(paginationQueryValue, out pageValue);
                if (pageValue != 0)
                {
                    int numberOfItemsToSkip = (pageValue - 1) * ItemService.ItemCountForSearchResult;

                    if (itemResultList != null && itemResultList.Count > numberOfItemsToSkip)
                    {
                        ViewBag.CurrentPage = pageValue;
                        itemResultList = itemResultList.Skip(numberOfItemsToSkip).Take(ItemService.ItemCountForSearchResult).ToList();
                    }
                }
            }
            else if (itemResultList != null && itemResultList.Count > 0)
            {
                itemResultList = itemResultList.Take(ItemService.ItemCountForSearchResult).ToList();
            }

            NameValueCollection queryStringCollection = new NameValueCollection(HttpContext.Request.QueryString);
            queryStringCollection.Remove(ItemService.PaginationQueryString);

            string excludedQueryStrings = string.Empty;
            if (queryStringCollection.Count > 0)
            {
                List<string> items = new List<string>();

                foreach (string name in queryStringCollection)
                    items.Add(string.Concat(name, "=", System.Web.HttpUtility.UrlEncode(queryStringCollection[name])));

                excludedQueryStrings = "?" + string.Join("?", items.ToArray());
            }

            ViewBag.ExcludedQueryStrings = excludedQueryStrings;
            #endregion

            ViewBag.SearchModel = itemSearchModel.CleanedSearchKey;
            return View(itemResultList);
        }

        public ActionResult SubSearchBoxView(string search)
        {
            ItemSearchModel itemSearchModel = new ItemSearchModel();
            itemSearchModel.SearchKey = search;
            return PartialView(itemSearchModel);
        }

        // POST: Search/SubSearchBoxView
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubSearchBoxViewPost([Bind(Include = "SearchKey")] ItemSearchModel itemSearchModelForFilter)
        {
            return RedirectToAction("Index", itemSearchModelForFilter);
        }

        public ActionResult Detail(int id)
        {
            ItemService itemService = new ItemService();
            ItemResultModel itemResultModel = itemService.GetByIDFromDB(id);

            if (ModelState.Count < 1) return RedirectToAction("Index");
            return View(itemResultModel);
        }
    }
}

Adneom.Adneotheque.Web/Views/Search/Detail.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel

@{
    ViewBag.Title = "Borrow Detail";
    Layout = "~/Views/Shared/_LayoutSub.cshtml";
    TempData["imageClass"] = "mx-auto d-block img-fluid detail_book_img";
    string categorySplitStr = string.Empty;
    string languageSplitStr = string.Empty;
}

<section class="detail_book">
    <div class="container">
        <div class="row">
            <div class="col-md-5 offset-1">
                @Html.Partial("ItemImageView", @Model)
            </div>
            <div class="col-md-6">
                <div class="col-md-12 pt-md-2 text-md-left">
                    <span class="detail_book_title">
                        @Model.Title
                    </span>
                </div>
                <div class="col-md-12 pt-md-2 text-md-left">
                    <span class="detail_book_author">
                        @Model.Authors
                    </span>
                </div>
                <div class="col-md-12 pt-md-2 text-md-left">
                    <span class="detail_book_rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                    </span>
                </div>
                <div class="col-md-12 pt-md-2 text-md-left">
                    <span class="detail_book_description">
                        <p>
                            @Model.Subtitle
                        </p>
                    </span>
                </div>
                <hr class="detail_book_hr">

                @if (!string.IsNullOrEmpty(Model.ISBN))
                {
                    <div class="row">
                        <div class="col-md-12 pt-md-2 text-md-left">

                            <span class="detail_book_title_tag">ISBN : </span>
                            <span class="detail_book_tags">@Model.ISBN</span>

                        </div>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.BorrowUserIdentity))
                {
                    <div class="row">
                        <div class="col-md-12 pt-md-2 text-md-left">

                            <span class="detail_book_title_tag">Booked By : </span>
                            <span class="detail_book_tags">@Adneom.Adneotheque.Common.Helpers.CommonHelpers.CleanUserDomain(Model.BorrowUserIdentity)</span>

                        </div>
                    </div>
                }
                <div class="row">
                    <div class="col-md-12 pt-md-2 text-md-left">
                        <span class="detail_book_title_tag">Category : </span>
                        @foreach (var itemCategory in Model.ItemCategories)
                        {
                            if (itemCategory.Category != null && !string.IsNullOrEmpty(itemCategory.Category.Name))
                            {
                                <span class="detail_book_tags">@categorySplitStr @itemCategory.Category.Name</span>
                            }
                            categorySplitStr = ",";
                        }
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 pt-md-2 text-md-left">
                        <span class="detail_book_title_tag">Language : </span>
                        @foreach (var itemLanguage in Model.ItemLanguages)
                        {
                            if (itemLanguage.Language != null && !string.IsNullOrEmpty(itemLanguage.Language.Name))
                            {
                                <span class="detail_book_tags">@languageSplitStr @itemLanguage.Language.Name</span>
                            }
                            languageSplitStr = ",";
                        }
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 pt-md-2 text-md-right">
                        @if (Model.Status != null)
                        {
                            if (Model.Status.ID == Adneom.Adneotheque.Domain.Models.Status.StatusModel.StatusEnum.Available.GetHashCode())
                            {
                                <button type="submit" name="process" class="btn btn-danger" onclick="location.href='@Url.Action("Apply","Borrow", new { id = Model.ID }, null)';"><i class="fab fa-leanpub"></i> Borrow</button>
                            }
                            else if (!string.IsNullOrEmpty(Model.BorrowUserIdentity) && Model.BorrowUserIdentity == User.Identity.Name)
                            {
                                <button type="submit" name="process" class="btn btn-info" onclick="location.href='@Url.Action("Apply","Return", new { id = Model.ID }, null)';"><i class="fab fa-undo-all"></i> Return</button>
                            }
                            else
                            {
                                if (Model.IsNotificationSent != true)
                                {
                                    <button type="submit" name="process" class="btn btn-info" onclick="location.href='@Url.Action("SendNotification","Borrow", new { id = Model.ID }, null)';">Send Notification</button>
                                }
                                else
                                {
                                    <span class="detail_book_tags">The notification is already sent before.</span>
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container offset-md-2">
        <div class="tab_container">
            <input id="tab1" type="radio" name="tabs" checked>
            <label for="tab1"><i class="fa fa-info-circle"></i><span>Description</span></label>
            <input id="tab2" type="radio" name="tabs">
            <label for="tab2"><i class="fa fa-comment"></i><span>Review</span></label>
            <section id="content1" class="tab-content">
                <p class="detail_book_tab_review">
                    @if (!string.IsNullOrEmpty(Model.Description))
                    {
                        @Model.Description
                    }
                    else
                    {
                        @Html.Raw("No description to show")
                    }
                </p>
            </section>
            <section id="content2" class="tab-content">
                <p class="detail_book_tab_review">
                    Coming soon...
                </p>
            </section>
        </div>
    </div>
</section>

Adneom.Adneotheque.Web/Views/Search/Index.cshtml
@model IList<Adneom.Adneotheque.Domain.Models.Item.ItemResultModel>

@{
    ViewBag.Title = "Search - All Books";
    Layout = "~/Views/Shared/_LayoutSub.cshtml";
    TempData["imageClass"] = "card-img-top img-fluid card";
    int currentPage = ViewBag.CurrentPage;
    int totalPageCount = ViewBag.TotalPageCount;
    int prevPageNum = currentPage - 1;
    int nextPageNum = currentPage + 1;
    string excludedQueryStrings = ViewBag.ExcludedQueryStrings;
    if (string.IsNullOrEmpty(excludedQueryStrings))
    {
        excludedQueryStrings = excludedQueryStrings + "?page=";
    }
    else
    {
        excludedQueryStrings = excludedQueryStrings + "&page=";
    }
}

<section class="search_bar">
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-1 d-block d-md-none logo">
                <img class="float-sm-right logo_header-2" src="/assets/pictures/Logo.png">
            </div>
            <div class="col-md-5">

                @Html.Action("SubSearchBoxView", "Search", new { search = ViewBag.SearchModel })

            </div>
            <div class="col-md-6 offset-1 d-none d-md-block logo">
                <img class="float-sm-right logo_header" src="/assets/pictures/Logo.png">
            </div>
        </div>
    </div>
</section>

<section class="all_books">
    <div class="container">
        <div class="row justify-content-center mb-3">
            <h1>ALL BOOKS</h1>
        </div>
        <div class="row">
            <div class="col-md-3 menu-left">
                @Html.Partial("SeachPageSideMenuView")
            </div>

            <div class="col-md-9 content_all-books">
                <div class="container">
                    <div class="row">
                        @if (Model != null && Model.Count > 0)
                        {
                            foreach (Adneom.Adneotheque.Domain.Models.Item.ItemResultModel item in Model)
                            {
                                <div class="col-lg-3 col-md-6">
                                    <div class="info-book">
                                        <span class="status">NEW</span>
                                        @Html.Partial("LanguageTagView", item)
                                    </div>

                                    @Html.Partial("ItemImageView", item)

                                    <div class="card-body">
                                        <a href="@Url.Action("Detail","Search", new { id = item.ID }, null)" class="card_book_link">
                                            <h4 class="card-title">@item.Title</h4>
                                        </a>
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            <h3 class="pb-3">No Result</h3>
                        }

                    </div>
                </div>

                @if (ViewBag.ShowPagination)
                {
                    <nav aria-label="Pagination">

                        <ul class="pagination justify-content-center">

                            @{
                                string prevLiClass = "page-item";
                                if (currentPage == 1)
                                {
                                    prevLiClass = "page-item disabled";
                                }
                            }

                            <li class="@prevLiClass">
                                <a class="page-link" href="@excludedQueryStrings@prevPageNum" tabindex="-1">Previous</a>
                            </li>

                            @for (int i = 1; i <= totalPageCount; i++)
                            {
                                if (i <= 3 || totalPageCount <= 6 || i >= 6)
                                {
                                    string liClass = "page-item";
                                    if (currentPage == i)
                                    {
                                        liClass = "page-item active disabled";
                                    }

                                    <li class="@liClass">
                                        <a class="page-link" href="@excludedQueryStrings@i">@i</a>
                                    </li>
                                }
                                else if (totalPageCount > 6 && currentPage == 3)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="#">...</a>
                                    </li>
                                }
                            }

                            @{
                                string nextLiClass = "page-item";
                                if (currentPage == totalPageCount)
                                {
                                    nextLiClass = "page-item disabled";
                                }
                            }

                            <li class="@nextLiClass">
                                <a class="page-link" href="@excludedQueryStrings@nextPageNum">Next</a>
                            </li>

                        </ul>
                    </nav>
                }

            </div>

        </div>
    </div>
</section>

@Html.Partial("NewBookRequestView")