Adneom.Adneotheque.Web/Controllers/ReturnController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Domain.Models.Item;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class ReturnController : Controller
    {
        // GET: Return
        public ActionResult Index()
        {
            IList<ItemResultModel> itemItemResultModelList = new List<ItemResultModel>();
            ItemService itemService = new ItemService();
            itemItemResultModelList = itemService.GetItemsToReturn();
            return View(itemItemResultModelList);
        }

        [HttpGet]
        // GET: Return/Apply/1
        public ActionResult Apply(int id)
        {
            if (id < 1) return RedirectToAction("Index");

            ItemService itemService = new ItemService();

            if (itemService.UpdateForReturn(id))
                return View("ReturnSuccessView");
            else
                return View("ReturnErrorView");
        }
    }
}

Adneom.Adneotheque.Web/Controllers/SearchController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Common.Helpers;
using Adneom.Adneotheque.Domain.Models.Item;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(ItemSearchModel itemSearchModel)
        {
            ItemService itemService = new ItemService();
            IList<ItemResultModel> itemResultList = new List<ItemResultModel>();

            if (!string.IsNullOrEmpty(itemSearchModel.SearchKey))
                itemResultList = itemService.GetItemToBorrow(itemSearchModel);
            else
                itemResultList = itemService.GetAll();

            itemResultList = itemService.GetUniqueResult(itemResultList);

            ViewBag.LanguageFilters = itemService.GetLanguageFilters(itemResultList);
            ViewBag.CategoryFilters = itemService.GetCategoryFilters(itemResultList);

            itemResultList = itemService.GetFilterResult(itemResultList);

            #region Pagination
            ViewBag.CurrentPage = 1;
            ViewBag.TotalPageCount = 1;
            ViewBag.ShowPagination = false;
            if (itemResultList != null && itemResultList.Count > ItemService.ItemCountForSearchResult)
                ViewBag.ShowPagination = true;

            if (itemResultList != null && itemResultList.Count > 0)
            {
                int i = itemResultList.Count / ItemService.ItemCountForSearchResult;
                decimal d = (decimal)itemResultList.Count / (decimal)ItemService.ItemCountForSearchResult;

                if (d > i)
                {
                    i = i + 1;
                }

                ViewBag.TotalPageCount = i;
            }

            string paginationQueryValue = CommonHelpers.GetCurrentQueryParameter(ItemService.PaginationQueryString);

            if (!string.IsNullOrEmpty(paginationQueryValue))
            {
                int pageValue = 0;
                int.TryParse(paginationQueryValue, out pageValue);
                if (pageValue != 0)
                {
                    int numberOfItemsToSkip = (pageValue - 1) * ItemService.ItemCountForSearchResult;

                    if (itemResultList != null && itemResultList.Count > numberOfItemsToSkip)
                    {
                        ViewBag.CurrentPage = pageValue;
                        itemResultList = itemResultList.Skip(numberOfItemsToSkip).Take(ItemService.ItemCountForSearchResult).ToList();
                    }
                }
            }
            else if (itemResultList != null && itemResultList.Count > 0)
            {
                itemResultList = itemResultList.Take(ItemService.ItemCountForSearchResult).ToList();
            }

            NameValueCollection queryStringCollection = new NameValueCollection(HttpContext.Request.QueryString);
            queryStringCollection.Remove(ItemService.PaginationQueryString);

            string excludedQueryStrings = string.Empty;
            if (queryStringCollection.Count > 0)
            {
                List<string> items = new List<string>();

                foreach (string name in queryStringCollection)
                    items.Add(string.Concat(name, "=", System.Web.HttpUtility.UrlEncode(queryStringCollection[name])));

                excludedQueryStrings = "?" + string.Join("?", items.ToArray());
            }

            ViewBag.ExcludedQueryStrings = excludedQueryStrings;
            #endregion

            ViewBag.SearchModel = itemSearchModel.CleanedSearchKey;
            return View(itemResultList);
        }

        public ActionResult SubSearchBoxView(string search)
        {
            ItemSearchModel itemSearchModel = new ItemSearchModel();
            itemSearchModel.SearchKey = search;
            return PartialView(itemSearchModel);
        }

        // POST: Search/SubSearchBoxView
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubSearchBoxViewPost([Bind(Include = "SearchKey")] ItemSearchModel itemSearchModelForFilter)
        {
            return RedirectToAction("Index", itemSearchModelForFilter);
        }

        public ActionResult Detail(int id)
        {
            ItemService itemService = new ItemService();
            ItemResultModel itemResultModel = itemService.GetByIDFromDB(id);

            if (ModelState.Count < 1) return RedirectToAction("Index");
            return View(itemResultModel);
        }
    }
}

Adneom.Adneotheque.Web/Views/Return/Index.cshtml
@model IList<Adneom.Adneotheque.Domain.Models.Item.ItemResultModel>

@{
    ViewBag.Title = "Return List";
    Layout = "~/Views/Shared/_LayoutSub.cshtml";
}

<link href="/assets/css/tableresponsive.css" rel="stylesheet">

<section>
    <div class="container pt-5">
        @if (Model != null && Model.Count > 0)
        {
            <h3 class="pb-3">You have booked @Model.Count books.</h3>
        }
        else
        {
            <h3 class="pb-3">You have no books.</h3>
        }
    </div>
</section>
@if (Model != null && Model.Count > 0)
{
    <section id="cd-table">
        <header class="cd-table-column">
            <h2>Informations</h2>
            <ul>
                <li>ISBN</li>
                <li>Date of borrow</li>
                <li>Date of return</li>
                <li>Action</li>
            </ul>
        </header>
        <div class="cd-table-container">
            <div class="cd-table-wrapper">

                @foreach (Adneom.Adneotheque.Domain.Models.Item.ItemResultModel item in Model)
                {
                    <div class="cd-table-column">
                        <h2>@item.Title</h2>
                        <ul>
                            <li>@item.ISBN</li>
                            <li>@Html.Raw(Adneom.Adneotheque.Common.Helpers.ItemHelper.GetItemBorrowDateStr(item.BorrowedDate))</li>
                            <li>@Html.Raw(Adneom.Adneotheque.Common.Helpers.ItemHelper.GetItemDateStrToReturn(item.BorrowedDate))</li>
                            <li>
                                <a class="btn btn-info mt-2" href="@Url.Action("Apply","Return", new { id = item.ID }, null)" role="button">Return</a>
                            </li>
                        </ul>
                    </div> <!-- cd-table-column -->
                }

            </div> <!-- cd-table-wrapper -->
        </div> <!-- cd-table-container -->
        <em class="cd-scroll-right"></em>
    </section> <!-- cd-table -->
}

Adneom.Adneotheque.Web/Views/Return/ReturnErrorView.cshtml
@{
    ViewBag.Title = "Return process is not succeeded";
    Layout = "~/Views/Shared/_LayoutSub.cshtml";
}

<section class="thankyou">
    <div id="top" class="text-center vertical-space" role="main">
        <div class="container">
            <div class="logo">
                <a href="@Url.Action("Index","Search")"><img src="/assets/pictures/check.png" alt="Check icon"></a>
            </div>
            <h1 class="headline">Return process is not succeeded! </h1>
            <h5 class="headline-support">Please contact to administration.</h5>
        </div>
    </div>
    <!-- //   Header Ends -->
    @Html.Partial("MessageCommonView")
</section>

Adneom.Adneotheque.Web/Views/Return/ReturnSuccessView.cshtml
@{
    ViewBag.Title = "Return process is succeeded";
    Layout = "~/Views/Shared/_LayoutSub.cshtml";
}

<section class="thankyou">
    <div id="top" class="text-center vertical-space" role="main">
        <div class="container">
            <div class="logo">
                <a href="@Url.Action("Index","Search")"><img src="/assets/pictures/check.png" alt="Check icon"></a>
            </div>
            <h1 class="headline">Thank you for your contribution! </h1>
        </div>
    </div>
    <!-- //   Header Ends -->
    @Html.Partial("MessageCommonView")
</section>