Adneom.Adneotheque.Web/Controllers/DonateController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Domain.Models.Item;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class DonateController : Controller
    {
        // GET: Donate/Search
        public ActionResult Search()
        {
            return View();
        }

        // POST: Donate/Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(ItemSearchModel itemSearchModel)
        {
            ItemResultModel itemResultModel = null;
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(itemSearchModel.SearchKey))
                {
                    ItemService itemService = new ItemService();
                    itemResultModel = itemService.GetItemToDonate(itemSearchModel);
                    return View("Detail", itemResultModel);
                }
            }

            return View(itemSearchModel);
        }

        // GET: Donate/Detail
        public ActionResult Detail()
        {
            if (ModelState.Count < 1) return RedirectToAction("Search");
            return View();
        }

        // POST: Donate/Detail
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Detail([Bind(Include = "ID,GoogleBooksVolumeID,Title,Subtitle,Description,Authors,Category,SelectedCategoryItems,SelectedLanguageItems,ISBN,LanguageCode")] ItemResultModel itemResultModel)
        {
            if (ModelState.IsValid)
            {
                ItemService itemService = new ItemService();
                if (itemService.Save(itemResultModel, ActionTypeService.ActionTypeEnum.Created))
                    return View("DonateSuccessView");
                else
                    return View("DonateErrorView");
            }

            return View(itemResultModel);
        }
    }
}

Adneom.Adneotheque.Web/Controllers/ReturnController.cs
using Adneom.Adneotheque.Business.Services;
using Adneom.Adneotheque.Domain.Models.Item;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Adneom.Adneotheque.Web.Controllers
{
    public class ReturnController : Controller
    {
        // GET: Return
        public ActionResult Index()
        {
            IList<ItemResultModel> itemItemResultModelList = new List<ItemResultModel>();
            ItemService itemService = new ItemService();
            itemItemResultModelList = itemService.GetItemsToReturn();
            return View(itemItemResultModelList);
        }

        [HttpGet]
        // GET: Return/Apply/1
        public ActionResult Apply(int id)
        {
            if (id < 1) return RedirectToAction("Index");

            ItemService itemService = new ItemService();

            if (itemService.UpdateForReturn(id))
                return View("ReturnSuccessView");
            else
                return View("ReturnErrorView");
        }
    }
}

Adneom.Adneotheque.Web/Views/Shared/BookPreview.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel

<script type="text/javascript" src="https://www.google.com/books/jsapi.js"></script>
<script type="text/javascript">
    var bookNO = 'ISBN:'+ @Model.ISBN;
    google.books.load();

    function initialize() {
        var viewer = new google.books.DefaultViewer(document.getElementById('viewerCanvas'));
        viewer.load(bookNO);
    }

    google.books.setOnLoadCallback(initialize);
</script>

@if (!string.IsNullOrEmpty(Model.GoogleBooksVolumeID) && !string.IsNullOrEmpty(Model.ISBN))
{
    <h4>You can preview <a href="https://books.google.be/books?id=@Model.GoogleBooksVolumeID.Trim()&dq=isbn:@Model.ISBN.Trim()" target="_blank">here. </a></h4>
}
<hr />

<div id="viewerCanvas" style="width: 900px; height: 1000px"></div>

Adneom.Adneotheque.Web/Views/Shared/CategoryDropDownListView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel

<div class="form-group">
    @Html.Label("Categories", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="styled-select">
        @Html.ListBoxFor(m => m.SelectedCategoryItems, new SelectList(Model.AllCategoryItems, "Name", "Name"), new { @class = "categoryDropDown", @multiple = "multiple" })
    </div>
</div>

Adneom.Adneotheque.Web/Views/Shared/FeaturedBooksView.cshtml
<!-- ALL BOOK -->
@{
    Adneom.Adneotheque.Business.Services.ItemService itemService = new Adneom.Adneotheque.Business.Services.ItemService();
    IList<Adneom.Adneotheque.Domain.Models.Item.ItemResultModel> itemList = itemService.GetFeaturedItems();    
    TempData["imageClass"] = "card-img-top img-fluid card";
}
<section class="list_books">
    <div class="container">
        <div class="row">

            @foreach (var item in itemList)
            {
            <div class="col-lg-3 col-md-6">
                <div class="info-book">
                    <span class="status">NEW</span>
                    @Html.Partial("LanguageTagView", item)
                </div>

                @Html.Partial("ItemImageView", item)

                <div class="card-body">
                    <a href="@Url.Action("Detail","Search", new { id = item.ID }, null)" class="card_book_link">
                        <h4 class="card-title">@item.Title</h4>
                    </a>
                </div>
            </div>
            }

        </div>
    </div>
</section>

Adneom.Adneotheque.Web/Views/Shared/ItemImageView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel
@{
    string imageClass = string.Empty;
    if (TempData["imageClass"] != null && !string.IsNullOrEmpty(TempData["imageClass"].ToString()))
    {
        imageClass = TempData["imageClass"].ToString();
    }
}

<img src="@Adneom.Adneotheque.Common.Helpers.ItemHelper.GetItemImageSrc(Model.GoogleBooksVolumeID)" alt="Image @Model.Title" class="@imageClass" />

Adneom.Adneotheque.Web/Views/Shared/LanguageDropDownListView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel

@*<div class="form-group">
    @Html.Label("Language", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="styled-select">
        @Html.DropDownListFor(model => model.LanguageCode, languageItems, "-- Select Language --", new { @class = "languageDropDown", @multiple = "multiple" })
    </div>
</div>*@

<div class="form-group">
    @Html.Label("Languages", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="styled-select">
        @Html.ListBoxFor(m => m.SelectedLanguageItems, new SelectList(Model.AllLanguageItems, "Name", "Name"), new { @class = "languageDropDown", @multiple = "multiple" })
    </div>
</div>

Adneom.Adneotheque.Web/Views/Shared/LanguageTagView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemResultModel

@if (Model.ItemLanguages != null && Model.ItemLanguages.Count > 0 && Model.ItemLanguages.FirstOrDefault() != null && Model.ItemLanguages.FirstOrDefault().Language != null && !string.IsNullOrEmpty(Model.ItemLanguages.FirstOrDefault().Language.Code))
{
    <span class="langue">@Model.ItemLanguages.FirstOrDefault().Language.Code.ToUpper()</span>
}

Adneom.Adneotheque.Web/Views/Shared/MainSearchBoxView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemSearchModel

<div class="container">
    <div class="row justify-content-left">
        <div class="col-md-10">
            <div class="content">
                <h1>Discover the world of<br> Books</h1>
                <h3>Join the Adneotheque now and start<br>reading</h3>
                <div class="col-md-12">

                    @using (Html.BeginForm("Index", "Search", FormMethod.Post, new { @class = "form-inline form-search" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.EditorFor(model => model.SearchKey, new { htmlAttributes = new { @class = "form-control input-search", @placeholder = "ISBN, Name, Author" } })
                        <input type="submit" value="Send" class="btn btn-form" />
                    }

                </div>

            </div>
        </div>
    </div>
</div>

Adneom.Adneotheque.Web/Views/Shared/MessageCommonView.cshtml
<p class="text-center"> <a href="@Url.Action("Index","Home")" class="btn btn-link"> ← Back to Home</a> </p>
<!-- Container -->
<div class="container">
    <section class="row">
        <div class="col-md-12">
            <!--<p class="text-center vertical-space">&copy; ADNEOM. All Rights Reserved</p>-->
        </div>
    </section>
    <!-- // End Client Logos -->
</div>

Adneom.Adneotheque.Web/Views/Shared/SeachPageSideMenuView.cshtml
@{
    var languageFilterModel = (IList<Adneom.Adneotheque.Domain.Models.Item.LanguageModel>)ViewBag.LanguageFilters;
    string languageQueryValue = Adneom.Adneotheque.Common.Helpers.CommonHelpers.GetCurrentQueryParameter(Adneom.Adneotheque.Business.Services.ItemService.LanguageQueryString);

    string availabilityQueryValue = Adneom.Adneotheque.Common.Helpers.CommonHelpers.GetCurrentQueryParameter(Adneom.Adneotheque.Business.Services.ItemService.AvailabilityQueryString);

    var categoryFilterModel = (IList<Adneom.Adneotheque.Domain.Models.Item.CategoryFilterModel>)ViewBag.CategoryFilters;
    string categoryQueryValue = Adneom.Adneotheque.Common.Helpers.CommonHelpers.GetCurrentQueryParameter(Adneom.Adneotheque.Business.Services.ItemService.CategoryQueryString);
}

<div class="filter_menu">
    <!-- Contenedor -->
    <ul class="menu">
        @*Language Starts*@
        <li>
            <div class="link">
                Language
                @if (!string.IsNullOrEmpty(languageQueryValue))
                {
                    <i class="far fa-check-square filtersOn"></i>
                }
                <i class="fa fa-chevron-down"></i>
            </div>
            <ul class="submenu">

                @foreach (Adneom.Adneotheque.Domain.Models.Item.LanguageModel languageItem in languageFilterModel)
                {
                    string lngNameWithCount = languageItem.Name + " (" + languageItem.Count + ")";
                    <li>
                        <div class="row">
                            <div class="col-md-9">
                                <span>@lngNameWithCount</span>
                            </div>
                            <div class="col-md-3 pt-md-2">
                                @Html.CheckBox(@languageItem.Name, new Dictionary<string, object>{
                                                {"id", "lng-"+@languageItem.Code},
                                                {"onclick","setCompleteStatus.call(this)"},
                                                {"data-filter", "language"},
                                                {"data-filter-value", @languageItem.Code},
                                                {languageQueryValue == languageItem.Code ? "checked": "data-checked","false"},
                                                {"class", "filter_checkbox"}})
                            </div>
                        </div>
                    </li>
                }

            </ul>
        </li>
        @*Language Ends*@

        @*Availability Starts*@
        <li>
            <div class="link">
                Available
                @if (!string.IsNullOrEmpty(availabilityQueryValue))
                {
                    <i class="far fa-check-square filtersOn"></i>
                }
                <i class="fa fa-chevron-down"></i>
            </div>
            <ul class="submenu">
                <li>
                    <div class="row">
                        <div class="col-md-9">
                            <span>@Html.Raw("Available")</span>
                        </div>
                        <div class="col-md-3 pt-md-2">
                            @Html.CheckBox("Available", new Dictionary<string, object>{
                                            {"id", "avb-1"},
                                            {"onclick","setCompleteStatus.call(this)"},
                                            {"data-filter", "availability"},
                                            {"data-filter-value", "1"},
                                            {availabilityQueryValue == "1" ? "checked": "data-checked","false"},
                                            {"class", "filter_checkbox"}})
                        </div>
                    </div>
                </li>
                <li>
                    <div class="row">
                        <div class="col-md-9">
                            <span>@Html.Raw("Booked")</span>
                        </div>
                        <div class="col-md-3 pt-md-2">
                            @Html.CheckBox("Booked", new Dictionary<string, object>{
                                            {"id", "avb-0"},
                                            {"onclick","setCompleteStatus.call(this)"},
                                            {"data-filter", "availability"},
                                            {"data-filter-value", "0"},
                                            {availabilityQueryValue == "0" ? "checked": "data-checked","false"},
                                            {"class", "filter_checkbox"}})
                        </div>
                    </div>
                </li>
            </ul>
        </li>
        @*Availability Ends*@

        @*Category Starts*@
        <li>
            <div class="link">
                Category
                @if (!string.IsNullOrEmpty(categoryQueryValue))
                {
                    <i class="far fa-check-square filtersOn"></i>
                }
                <i class="fa fa-chevron-down"></i>
            </div>
            <ul class="submenu">
                @foreach (Adneom.Adneotheque.Domain.Models.Item.CategoryFilterModel categoryItem in categoryFilterModel)
                {
                    string catNameWithCount = categoryItem.Name + " (" + categoryItem.Count + ")";
                    <li>
                        <div class="row">
                            <div class="col-md-9">
                                <span>@catNameWithCount</span>
                            </div>
                            <div class="col-md-3 pt-md-2">
                                @Html.CheckBox(@categoryItem.Name, new Dictionary<string, object>{
                                                {"id", "lng-"+@categoryItem.ID},
                                                {"onclick","setCompleteStatus.call(this)"},
                                                {"data-filter", "category"},
                                                {"data-filter-value", @categoryItem.ID},
                                                {categoryQueryValue == categoryItem.ID.ToString() ? "checked": "data-checked","false"},
                                                {"class", "filter_checkbox"}})
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </li>
        @*Category Ends*@

        @*Rating Starts*@
        <li>
            <div class="link">Rating<i class="fa fa-chevron-down"></i></div>
            <ul class="submenu">
                <li><a href="#">5 stars</a></li>
                <li><a href="#">4 stars</a></li>
                <li><a href="#">3 stars</a></li>
                <li><a href="#">2 stars</a></li>
                <li><a href="#">1 stars</a></li>
            </ul>
        </li>
        @*Rating Ends*@
    </ul>
</div>

Adneom.Adneotheque.Web/Views/Shared/SubSearchBoxView.cshtml
@model Adneom.Adneotheque.Domain.Models.Item.ItemSearchModel
<div id="wrap">
    @using (Html.BeginForm("SubSearchBoxViewPost", "Search", FormMethod.Post, new { @class = "navbar-form", @role = "search" }))
    {
        <div class="input-group">
            @Html.AntiForgeryToken()
            @Html.EditorFor(model => model.SearchKey, new { htmlAttributes = new { @id = "search", @class = "searchtop", @placeholder = "ISBN, Name, Author" } })
            <div class="input-group-btn">
                <input type="submit" value="Search" class="btn btn-form" id="search_submit" />
            </div>
        </div>
    }
</div>

Adneom.Adneotheque.Web/Views/Shared/UserInfoView.cshtml
@if (User != null && User.Identity != null && !string.IsNullOrEmpty(User.Identity.Name))
{
    <li>
        <a class="btn btn-navy" href="@Url.Action("Index","Return")">
            <span class="Logo-Title">Hello,  @Adneom.Adneotheque.Common.Helpers.CommonHelpers.CleanUserDomain(User.Identity.Name)</span>
        </a>
    </li>
}

Adneom.Adneotheque.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewBag.Title - Adneotheque</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/css/adneotheque.css" rel="stylesheet">
    <!--[if IE]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

    <section class="homepage">
        <!--============================= HEADER =============================-->
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <a class="navbar-brand" href="@Url.Action("Index","Home")">
                                <span class="Logo-Title">Adneotheque</span>
                            </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                                <ul class="navbar-nav">
                                    <li>
                                        <a href="@Url.Action("About","Home")" class="btn btn-navy">About</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index","Search")" class="btn btn-navy">See All Books</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Search","Donate")" class="btn btn-navy">Donate</a>
                                    </li>
                                    @Html.Partial("UserInfoView")
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </header>

        <!--//END HEADER -->
        <!--============================= Content =============================-->

        @RenderBody()

    </section>
    <!--//END Content -->

    @Html.Partial("FeaturedBooksView")

    <!-- footer start -->
    <footer class="footer-area">
        <div class="footer-bottom">
            <div class="container">
                <div class="row footer-content">
                    <div class="col-md-6">
                        <div class="footer-left">
                            <img class="logo_footer" src="/assets/pictures/Logo.png">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-right">
                            <span>&copy; @DateTime.Now.Year <span class="company_name">ADNEOM</span></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer End -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/assets/js/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/adneotheque.js"></script>
</body>
</html>

Adneom.Adneotheque.Web/Views/Shared/_LayoutError.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>404 Error Template for Bootstrap</title>
    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/css/fontawesome-all.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/404.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/assets/js/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>

Adneom.Adneotheque.Web/Views/Shared/_LayoutSub.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">
    <title>@ViewBag.Title - Adneotheque</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/css/fontawesome-all.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/css/style.css" rel="stylesheet">
    <!--[if IE]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

    <!--============================= HEADER =============================-->
    <!-- Top menu -->
    <section class="navbar_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-green">
                        <a class="navbar-brand" href="@Url.Action("Index","Home")">Adneotheque</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index","Search")">See All Books</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Search","Donate")">Donate</a>
                                </li>
                                @Html.Partial("UserInfoView")
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    <!--============================= Content =============================-->

    @RenderBody()

    <!--//END Content -->
    <!-- footer start -->
    <footer class="footer-area">
        <div class="footer-bottom">
            <div class="container">
                <div class="row footer-content">
                    <div class="col-md-6">
                        <div class="footer-left">
                            <img class="logo_footer" src="/assets/pictures/Logo.png">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-right">
                            <span>&copy; @DateTime.Now.Year <span class="company_name">ADNEOM</span></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer End -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/assets/js/jquery-3.3.1.min.js"><\/script>')</script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/fontawesome.js"></script>
    <script src="/assets/js/adneotheque.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>*@

    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.js"></script>
    <script>
        $(document).ready(function () {
            $('.categoryDropDown').select2({
                tags: true,
                tokenSeparators: [',']
            });

            $('.languageDropDown').select2({
                tags: true,
                tokenSeparators: [',']
            });

            $('.js-example-basic-multiple').select2({
                tags: true,
                tokenSeparators: [',']
            });
        });
    </script>
</body>
</html>